service: offer-notification-application

frameworkVersion: '2 || 3'

useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  # List of the permissions that the lambda function needs to work properly
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 'sns:Publish'
          Resource:
            - Ref: OfferTopic

# The list of the lambda functions
functions:
# The lambda function that crawls the target website and publishes a notification
  crawl:
    handler: src/handler.run
    environment:
    # The OfferTopic ARN where the notification will be published
      OFFER_TOPIC_ARN: !Ref OfferTopic
    events:
    # The event which will trigger the lambda function
      - schedule: rate(1 day)

# AWS resources which needs to be provisioned
resources:
  Resources:
  # The SNS topic where the notifications about the offers will be published
    OfferTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: offer-topic
        Subscription:
        # Subscribe to this topic with an email address
          - Endpoint: ${env:EMAIL}
            Protocol: email